version: '3'

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: tgen
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: mysql
      MYSQL_PASSWORD: supersecret
      DATABASE_HOST: db


  avahi:
    build: ./avahi_daemon
    depends_on:
      - db


  web:
    build: ./web
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tgen
      MYSQL_USER: mysql
      MYSQL_PASSWORD: supersecret
    ports:
      - "3257:3257"
    depends_on:
      - db
      - avahi
    restart: on-failure 


  
