version: '2.1'

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: tgen
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: mysql
      MYSQL_PASSWORD: supersecret
      DATABASE_HOST: db
    networks:
      web_net:
        ipv4_address: 172.22.0.2
        ipv6_address: 2001:3984:3989::10

  avahi:
    build: ./avahi_daemon
    depends_on:
      - db
    networks:
      web_net:
        ipv4_address: 172.22.0.3
        ipv6_address: 2001:3984:3989::11

  web:
    build: ./web
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tgen
      MYSQL_USER: mysql
      MYSQL_PASSWORD: supersecret
    ports:
      - "3257:3257"
    depends_on:
      - db
      - avahi
    networks:
      web_net:
        ipv4_address: 172.22.0.4
        ipv6_address: 2001:3984:3989::9
    restart: on-failure

networks:
  web_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24
      - subnet: 2001:3984:3989::/64
        




  
